# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: microget 1.1.2 ruby lib

Gem::Specification.new do |s|
  s.name = "microget"
  s.version = "1.1.3"
  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Julik Tarkhanov"]
  s.description = "Pedal-to-the-metal HTTP client for GET requests"
  s.email = "me@julik.nl"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files         = Dir.chdir(File.expand_path('..', __FILE__)) do
    `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^(test|spec|features)/}) }
  end
  s.homepage = "http://github.com/julik/microget"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Designed for slow and/or large response bodies"

  s.specification_version = 4
  s.add_development_dependency(%q<rake>, ["~> 10"])
  s.add_development_dependency(%q<puma>, [">= 0"])
  s.add_development_dependency(%q<rack>, ["~> 2"])
  s.add_development_dependency(%q<yard>, [">= 0"])
  s.add_development_dependency(%q<rspec>, ["< 3.3", "~> 3.2.0"])
  s.add_development_dependency(%q<bundler>, ["~> 1.0"])
end

